# Generated by Django 3.2.16 on 2023-02-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_var', models.CharField(max_length=64, unique=True, verbose_name='на английском')),
                ('rus_var', models.CharField(max_length=64, unique=True, verbose_name='на русском')),
            ],
        ),
    ]
