# Generated by Django 3.2.16 on 2023-02-13 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part_of_speech",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True, verbose_name="имя части речи")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
            ],
        ),
        migrations.AddField(
            model_name="words",
            name="category",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="mainapp.part_of_speech"
            ),
        ),
    ]
